=== DaveLiddament/phpsw-ng/data/json-schema/events.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Event",
    "description": "This defines an event (meetup)",
    "type": "object",
    "properties": {
        "meetup-id": {
            "description": "The meetup ID",
            "type": "string"
        },
        "date": {
            "description": "Date of the event",
            "type": "string"
        },
        "start-time": {
            "description": "Start time of the event",
            "type": "string"
        },
        "end-time": {
            "description": "End time of the event",
            "type": "string"
        },
        "title": {
            "description": "Event's title",
            "type": "string"
        },
        "description": {
            "description": "Event's description",
            "type": "string"
        },
        "talks": {
            "description": "Talks",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "venue": {
            "description": "Event's location",
            "type": "string"
        },
        "pub": {
            "description": "Pub afterwards",
            "type": "string"
        },
        "organisers": {
            "description": "A list of the organisers",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "sponsors": {
            "description": "Event sponsors",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "joindin-url": {
            "description": "Link to the joind.in event",
            "type": "string"
        }
    },
    "required": ["date", "title"]
}

=== DaveLiddament/phpsw-ng/data/events/drafts/2012-10-10-talks-on-zend-framework-1-to-zend-framework-2-and-website-optimisation.json
{
    "title": "Talks on Zend Framework 1 to Zend Framework 2 and Website Optimisation",
    "description": "",
    "date": "10 October 2012",
    "meetup-id": "85545952",
    "start-time": "01:05",
    "end-time": "21:00",
    "talks": [],
    "venue": "golden-guinea",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/events/drafts/2012-12-12-christmas-booze-up.json
{
    "title": "Christmas Booze-up",
    "description": "<p>A chance to eat pizza, drink fine beer and be generally merry!<\/p> <p>Talks on:<\/p> <p>The Future of Humanity FuelPHP The Cleanest Code: or, Uncle Bob Driven Development (UBDD) <a href=\"http:\/\/brightpearl.com\/\">Brightpearl<\/a> have generously offered to sponsor this event, so it will be hosted in the Brightpearl offices (between Cabot Circus and Portland Square). There will be beer (free as in beer), pizza (also free as in beer) and assorted revelry.<\/p> <p>Places may be limited so please RSVP.<\/p> <p>\u00a0<\/p> <p><i>Driving to this event is not to be recommended.<\/i><\/p> ",
    "date": "12 December 2012",
    "meetup-id": "91339382",
    "start-time": "19:00",
    "end-time": "21:00",
    "talks": [],
    "venue": "brightpearl",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/drafts/2013-04-30-first-meetup-of-the-year.json
{
    "title": "First meetup of the year",
    "description": "<p>There will be a talk on software design, OO stuff, unit testing with PHP examples.<\/p> <p>If anyone else would like to talk about something similar to the above or anything PHP, please contact me.<\/p> <p>Room is booked from 6.30pm. Talk will not start until after 7pm.<\/p> <p>\u00a0<\/p> <p>\u00a0<\/p> <p>\u00a0<\/p> <p>\u00a0<\/p> <p>\n\n\n\n\n\u00a0<\/p> <p>\u00a0<\/p> ",
    "date": "30 April 2013",
    "meetup-id": "114007332",
    "start-time": "05:05",
    "end-time": "21:00",
    "talks": [],
    "venue": "stag-and-hounds",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/drafts/2011-12-14-talk-php.json
{
    "title": "Talk PHP",
    "description": "",
    "date": "14 December 2011",
    "meetup-id": "41633642",
    "start-time": "17:05",
    "end-time": "21:00",
    "talks": [],
    "venue": "golden-guinea",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/events/drafts/2014-04-09-social-night.json
{
    "title": "Social Night",
    "description": "<p>Meet up and talk about beer, how exciting May is going to be, and maybe even PHP too.<\/p> <p><a href=\"http:\/\/www.smallbarbristol.com\" class=\"linkified\">http:\/\/www.smallbarbristol.com<\/a><\/p> ",
    "date": "9 April 2014",
    "meetup-id": "168633652",
    "start-time": "01:04",
    "end-time": "21:00",
    "talks": [],
    "venue": "small-bar",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/drafts/2012-02-08-talks-on-zend-framework-2-and-one-other-tbc.json
{
    "title": "Talks on Zend Framework 2 and one other TBC",
    "description": "<p>We'll have one or two short talks. Plus the usual chat about PHP, general tech and whatever else.<\/p> ",
    "date": "8 February 2012",
    "meetup-id": "47790032",
    "start-time": "17:09",
    "end-time": "21:00",
    "talks": [],
    "venue": "golden-guinea",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/drafts/2014-01-08-social-night.json
{
    "title": "Social Night",
    "description": "<p>Meet up and talk about beer and new years, and maybe even PHP too.<\/p> <p>Venue: Horts, Broad Street -\u00a0<a href=\"http:\/\/www.hortsbristol.com\" class=\"linkified\">http:\/\/www.hortsbristol.com<\/a><\/p> ",
    "date": "8 January 2014",
    "meetup-id": "156650922",
    "start-time": "17:03",
    "end-time": "21:00",
    "talks": [],
    "venue": "horts",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/events/drafts/2012-04-11-talks-on-javascript-unit-backbone-testing-and-symfony2.json
{
    "title": "Talks on Javascript (Unit|Backbone) Testing and Symfony2",
    "description": "<p><b>Javascript Testing<\/b> (Andrew Martin)<\/p> <p>JS Unit Testing: The State of the Art Backbone Model\/View\u00a0Testing \u00a0<\/p> <p><b>Symfony2<\/b> (Dom Udall)<\/p> <p>Symfony2: An Overview \u00a0<\/p> <p>To be preceded, followed and interrupted by beer, Mexico's finest chilli and vocal dissent.<\/p> ",
    "date": "11 April 2012",
    "meetup-id": "58053142",
    "start-time": "01:01",
    "end-time": "21:00",
    "talks": [],
    "venue": "golden-guinea",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}
