=== DaveLiddament/phpsw-ng/data/json-schema/events.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Event",
    "description": "This defines an event (meetup)",
    "type": "object",
    "properties": {
        "meetup-id": {
            "description": "The meetup ID",
            "type": "string"
        },
        "date": {
            "description": "Date of the event",
            "type": "string"
        },
        "start-time": {
            "description": "Start time of the event",
            "type": "string"
        },
        "end-time": {
            "description": "End time of the event",
            "type": "string"
        },
        "title": {
            "description": "Event's title",
            "type": "string"
        },
        "description": {
            "description": "Event's description",
            "type": "string"
        },
        "talks": {
            "description": "Talks",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "venue": {
            "description": "Event's location",
            "type": "string"
        },
        "pub": {
            "description": "Pub afterwards",
            "type": "string"
        },
        "organisers": {
            "description": "A list of the organisers",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "sponsors": {
            "description": "Event sponsors",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "joindin-url": {
            "description": "Link to the joind.in event",
            "type": "string"
        }
    },
    "required": ["date", "title"]
}

=== DaveLiddament/phpsw-ng/data/events/drafts/2012-03-14-talk-on-unit-testing-and-one-other-tba.json
{
    "title": "Talk on unit testing and one other TBA",
    "description": "",
    "date": "14 March 2012",
    "meetup-id": "53990912",
    "start-time": "17:07",
    "end-time": "21:00",
    "talks": [],
    "venue": "golden-guinea",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/events/drafts/2012-09-05-talks-on-composer-and-silverstripe.json
{
    "title": "Talks on Composer and Silverstripe",
    "description": "",
    "date": "5 September 2012",
    "meetup-id": "78830502",
    "start-time": "19:00",
    "end-time": "21:00",
    "talks": [],
    "venue": "golden-guinea",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/events/drafts/2012-06-20-profiling-and-debugging-php.json
{
    "title": "Profiling and debugging PHP",
    "description": "<p>Talks on PHP profiling and debugging<\/p> ",
    "date": "20 June 2012",
    "meetup-id": "65851242",
    "start-time": "01:09",
    "end-time": "21:00",
    "talks": [],
    "venue": "golden-guinea",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/events/drafts/2013-04-03-meetup-social-and-php-chat.json
{
    "title": "Meetup - Social & PHP chat",
    "description": "<p>Hi Adrian &amp; All,<\/p> <p>Wanted to suggest a social\/ chance to talk PHP.<br\/>Hope this is ok.<\/p> <p>Best wishes,<br\/>Indu<\/p> ",
    "date": "3 April 2013",
    "meetup-id": "109724772",
    "start-time": "20:00",
    "end-time": "21:00",
    "talks": [],
    "venue": "king-william",
    "pub": "",
    "organisers": [
        "kat-zien",
        "dave-liddament",
        "lee-stone",
        "oliver-davies"
    ],
    "sponsors": [
        "basekit",
        "brightpearl",
        "deep-blue-sky",
        "ents24",
        "equiniti",
        "meanbee"
    ],
    "joindin-url": "https:\/\/joind.in\/event\/phpsw-"
}

=== DaveLiddament/phpsw-ng/data/events/the-final-pipeline.json
{
  "description" : "In November we present 'The Final Pipeline' (sung to the tune of the final countdown...) ",
  "date" : "November 2017",
  "meetup-id" : "244528361",
  "organisers" : [
    "lee-stone",
    "dave-liddament",
    "kat-zien",
    "oliver-davies"
  ],
  "pub" : "volunteer-tavern",
  "venue" : "basekit",
  "sponsors" : [
    "basekit",
    "brightpearl",
    "deep-blue-sky",
    "ents24",
    "equiniti",
    "meanbee"
  ],
  "title" : "The Final Pipeline"
}

=== DaveLiddament/phpsw-ng/data/events/new-year-new-topics.json
{
  "title": "New Year, New Topics",
  "description": "In January we present 'New Year, New Topics', a collection of talks on topics we haven't featured much (if at all) at PHPSW.",
  "date": "10 January 2018",
  "meetup-id": "246355497",
  "start-time": "19:00",
  "end-time": "21:00",
  "talks": [
    "command-and-(e)mission-control",
    "http-caching-improving-performance-saving-the-ice-caps"
  ],
  "venue": "basekit",
  "pub": "volunteer-tavern",
  "organisers": [
    "lee-stone",
    "dave-liddament",
    "kat-zien",
    "oliver-davies"
  ],
  "sponsors": [
    "basekit",
    "brightpearl",
    "deep-blue-sky",
    "ents24",
    "equiniti",
    "meanbee"
  ],
  "joindin-url": "https://joind.in/event/phpsw-new-year-new-topics-january-2018"
}
