=== DaveLiddament/phpsw-ng/data/json-schema/locations.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Location",
    "description": "This defines our locations (venues and pub)",
    "type": "object",
    "properties": {
        "name": {
            "description": "Name of the location",
            "type": "string"
        },
        "address": {
            "description": "Address",
            "type": "string"
        },
         "postcode": {
            "description": "Postcode",
            "type": "string"
        },
        "website-url": {
            "description": "A link to the location's website (optional)",
            "type": "string"
        },
        "maps-url": {
            "description": "A link to google maps",
            "type": "string"
        }
    },
    "required": ["name", "address", "postcode", "maps-url"]
}

=== DaveLiddament/phpsw-ng/data/locations/basekit-office.json
{
  "name": "BaseKit Office",
  "address": "4th Floor, The Pithay",
  "postcode": "BS1 2ND",
  "website-url": "https://www.basekit.com/",
  "maps-url": "https://www.google.co.uk/maps/place/Pithay,+Bristol+BS1+3BN/@51.455749,-2.5942937,17z/data=!3m1!4b1!4m5!3m4!1s0x48718e7771d6d179:0x81663ca0dd2a2109!8m2!3d51.4557591!4d-2.5920657?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/king-william.json
{
  "name": "King William Ale House",
  "address": "20 King St, Bristol",
  "postcode": "BS1 4EF",
  "website-url": "",
  "maps-url": "https://www.google.co.uk/maps/place/King+William+Ale+House/@51.4511729,-2.5712227,13z/data=!4m8!1m2!2m1!1sThe+King+William+Bristol!3m4!1s0x48718e7885a88e91:0x9294bb860628f830!8m2!3d51.4516718!4d-2.5948646?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/golden-guinea.json
{
  "name": "The Golden Guinea",
  "address": "19 Guinea St, Bristol",
  "postcode": "BS1 6SX",
  "website-url": "http://thegoldenguinea.co.uk",
  "maps-url": "https://www.google.co.uk/maps/place/The+Golden+Guinea/@51.4475036,-2.5940756,14z/data=!4m12!1m6!3m5!1s0x48718e7f0f4fe145:0x60909a6b44aa3ebb!2sThe+Golden+Guinea!8m2!3d51.4473612!4d-2.5928274!3m4!1s0x48718e7f0f4fe145:0x60909a6b44aa3ebb!8m2!3d51.4473612!4d-2.5928274?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/edo.json
{
  "name": "Edo",
  "address": "The Quorum, Bond St, Bristol BS1 3AE, UK",
  "postcode": "BS1 3AE",
  "website-url": "https://www.edo.co/",
  "maps-url": "https://www.google.com/maps/place/Edo/@51.4561053,-2.5854633,17z/data=!3m1!4b1!4m5!3m4!1s0x48718e7848e61129:0x5c939da1cf9c07bb!8m2!3d51.4561053!4d-2.5832746?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/stag-and-hounds.json
{
  "name": "Stag & Hounds",
  "address": "74 Old Market St, Bristol",
  "postcode": "BS2 0EJ",
  "website-url": "http://www.stagandhoundsbristol.co.uk",
  "maps-url": "https://www.google.com/maps/place/Stag+%26+Hounds/@51.4556425,-2.5846548,17z/data=!4m13!1m7!3m6!1s0x48718e6ff1a744fb:0x332866577b3501fb!2sStag+%26+Hounds,+74+Old+Market+St,+Bristol+BS2+0EJ!3b1!8m2!3d51.4556425!4d-2.5824661!3m4!1s0x48718e6ffa54a4fb:0x59ab2d0c988ec258!8m2!3d51.4556075!4d-2.5829274?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/small-bar.json
{
  "name": "Small Bar",
  "address": "31 King St, Bristol",
  "postcode": "BS1 4DZ",
  "website-url": "http://www.smallbar.co.uk",
  "maps-url": "https://www.google.co.uk/maps/place/Small+Bar/@51.4518433,-2.5972218,17z/data=!3m1!4b1!4m5!3m4!1s0x48718e788440afcb:0x4d6c80ad935768c8!8m2!3d51.4518433!4d-2.5950331?hl=en"
}
