=== DaveLiddament/phpsw-ng/data/json-schema/locations.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Location",
    "description": "This defines our locations (venues and pub)",
    "type": "object",
    "properties": {
        "name": {
            "description": "Name of the location",
            "type": "string"
        },
        "address": {
            "description": "Address",
            "type": "string"
        },
         "postcode": {
            "description": "Postcode",
            "type": "string"
        },
        "website-url": {
            "description": "A link to the location's website (optional)",
            "type": "string"
        },
        "maps-url": {
            "description": "A link to google maps",
            "type": "string"
        }
    },
    "required": ["name", "address", "postcode", "maps-url"]
}

=== DaveLiddament/phpsw-ng/data/locations/horts.json
{
  "name": "Horts",
  "address": "49 Broad St, Bristol",
  "postcode": "BS1 2EP",
  "website-url": "http://www.hortsbristol.com",
  "maps-url": "https://www.google.co.uk/maps/place/Horts/@51.4554877,-2.5960549,17z/data=!3m1!4b1!4m5!3m4!1s0x48718e7791fd35eb:0x912174706bcf4525!8m2!3d51.4554877!4d-2.5938662?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/brightpearl.json
{
  "name": "Brightpearl",
  "address": "New Bond House, Bond Street, Bristol BS2 9AG, UK",
  "postcode": "BS2 9AG",
  "website-url": "https://www.brightpearl.com/",
  "maps-url": "https://www.google.com/maps/place/Brightpearl/@51.4598061,-2.5864296,17z/data=!3m1!4b1!4m5!3m4!1s0x48718e71f99fca99:0xa006f70b6f44cbd3!8m2!3d51.4598061!4d-2.5842409?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/desklodge.json
{
  "name": "DeskLodge",
  "address": "1 Temple Way, Bristol BS2 0BY, UK",
  "postcode": "BS2 0BY",
  "website-url": "https://desklodge.com/",
  "maps-url": "https://www.google.com/maps/place/DeskLodge/@51.4548311,-2.5850307,17z/data=!3m1!4b1!4m5!3m4!1s0x48761b40aba643fb:0xbca2fa66dbdb1d5b!8m2!3d51.4548311!4d-2.582842?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/volunteer-tavern.json
{
  "name": "Volunteer Tavern",
  "address": "9 New St, Near Cabot Circus, Bristol",
  "postcode": "BS2 9DX",
  "website-url": "http://volunteertavern.co.uk/",
  "maps-url": "https://www.google.co.uk/maps/place/Volunteer+Tavern/@51.4576774,-2.5842452,17z/data=!3m1!4b1!4m5!3m4!1s0x48718e6fb529ad6f:0xd6b9ce794b9c0273!8m2!3d51.4576741!4d-2.5820565"
}

=== DaveLiddament/phpsw-ng/data/locations/mix-radio.json
{
  "name": "MixRadio",
  "address": "Prudential Buildings, 11-19 Wine St, Bristol",
  "postcode": "BS1 2PH",
  "website-url": "http://www.mixradiomusic.com",
  "maps-url": "https://www.google.com/maps/place/The+Prudential+Buildings/@51.4553799,-2.5945477,17z/data=!4m8!1m2!2m1!1sPrudential+Buildings,+11-19+Wine+St.,+Bristol,+BS1+2PH,+Bristol,+Bristol,+gb!3m4!1s0x48718e7742bdbdd9:0xc765bd29f2f938db!8m2!3d51.4553157!4d-2.5923703?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/bristol-ram.json
{
  "name": "The Bristol Ram",
  "address": "32 Park St, West End, Bristol",
  "postcode": "BS1 5JA",
  "website-url": "http://www.thebristolram.co.uk",
  "maps-url": "https://www.google.co.uk/maps/place/The+Bristol+Ram/@51.4540211,-2.6041633,17z/data=!3m1!4b1!4m5!3m4!1s0x48718dd0ad58c6e9:0x90c98c3f76775b5e!8m2!3d51.4540211!4d-2.6019746?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/royal-navy-volunteer.json
{
  "name": "The Famous Royal Navy Volunteer",
  "address": "17-18 King Street, Old City, Bristol",
  "postcode": "BS1 4EF",
  "website-url": "http://navyvolunteer.co.uk",
  "maps-url": "https://www.google.co.uk/maps/place/The+Famous+Royal+Navy+Volunteer/@51.4517519,-2.5967742,17z/data=!3m1!4b1!4m5!3m4!1s0x48718e788e56b41f:0x86dcd201a5ea99b8!8m2!3d51.4517519!4d-2.5945855?hl=en"
}

=== DaveLiddament/phpsw-ng/data/locations/basekit.json
{
  "name": "BaseKit",
  "address": "5th Floor One Castle Park, Tower Hill, Bristol BS2 0JA, UK",
  "postcode": "BS2 0JA",
  "website-url": "https://www.basekit.com/",
  "maps-url": "https://www.google.com/maps/place/BaseKit/@51.4553045,-2.5869773,17z/data=!3m1!4b1!4m5!3m4!1s0x48718e7771c6e43b:0x57389bdc2634249e!8m2!3d51.4553045!4d-2.5847886?hl=en"
}
