=== DaveLiddament/phpsw-ng/data/json-schema/people.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Person",
  "description": "This defines a person, they may be a speaker or an organiser (not an attendee)",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the person",
      "type": "string"
    },
    "photo-url": {
      "description": "URL of a photo of the person",
      "type": "string"
    },
    "description": {
      "description": "Brief description about the person (e.g. lead developer at Acme Co.)",
      "type": "string"
    },
    "twitter-handle": {
      "description": "Person's twitter handle",
      "type": "string"
    },
    "github-url": {
      "description": "Person's github URL ",
      "type": "string"
    },
    "website-url": {
      "description": "Person's website (or link to their meetup profile)",
      "type": "string"
    },
    "meetup-id": {
      "description": "Person's meetup ID",
      "type": "integer"
    }
  },
  "required": ["name", "photo-url", "description"]
}

=== DaveLiddament/phpsw-ng/data/people/stuart-herbert.json
{
    "name": "Stuart Herbert",
    "photo-url": "https://secure.meetupstatic.com/photos/member/b/7/2/c/highres_24046892.jpeg",
    "description": "Software industry veteran. Developer. Leader. Teacher. QA. Building quality at Ganbaro Digital.",
    "twitter-handle": "stuherbert",
    "website-url": "http://blog.stuartherbert.com/",
    "meetup-id": 25201422
}
